stages:
  - check
  - android
  - ios

variables:
  LC_ALL: "en_US.UTF-8"
  LANG: "en_US.UTF-8"

before_script:
  - mkdir -p `pwd`/.gradle
  - export GRADLE_USER_HOME=`pwd`/.gradle

# Common

check:
  stage: check
  image: betomorrow/ci-node:12_v1
  script:
    - npm ci --progress=false
    - npm run tsc
    - npm run lint
    # - npm run test -- --ci  # none for now
  only:
    - merge_requests
    - branches

# Android

android:build:dev:
  extends: .build-android
  variables:
    ENV: dev
  only:
    - master

android:build:demo:
  extends: .build-android
  variables:
    ENV: demo
  only:
    - demo

android:build:prod:
  extends: .build-android
  variables:
    ENV: prod
  only:
    - prod

.build-android:
  stage: android
  image: betomorrow/ci-android:29_v1
  environment:
    name: ${ENV}
  tags:
    - react-native
    - android
  before_script:
    - mkdir -p `pwd`/.gradle
    - export GRADLE_USER_HOME=`pwd`/.gradle
    - mkdir artifacts
  script:
    - npm ci --progress=false
    - npx jetifier
    - bash ./scripts/copy-env.sh ${ENV}
    - cd android
    # Export Signing Config
    - cat ${RELEASE_KEYSTORE_BASE64} | base64 -d > circular.release.keystore
    - echo "keystorePath=../circular.release.keystore" > signing.properties
    - echo "keystorePassword=$RELEASE_KEYSTORE_PASSWORD" >> signing.properties
    - echo "keyAlias=$RELEASE_KEY_ALIAS" >> signing.properties
    - echo "keyPassword=$RELEASE_KEY_PASSWORD" >> signing.properties
    # Export Google Api KeY
    - cat ${GOOGLE_API_KEY_BASE64} | base64 -d > googleApiKey.json
    # Build
    - bundle install
    - bundle exec fastlane ${ENV}

#   IOS

ios:build:dev:
  extends: .build-ios
  variables:
    ENV: dev
  only:
    - master

ios:build:demo:
  extends: .build-ios
  variables:
    ENV: demo
  only:
    - demo

ios:build:prod:
  extends: .build-ios
  variables:
    ENV: prod
  only:
    - prod

.build-ios:
  stage: ios
  environment:
    name: ${ENV}
  variables:
    LC_ALL: "en_US.UTF-8"
    LANG: "en_US.UTF-8"
  tags:
    - react-native
    - ios-12.2
    - latest
  script:
    - npm ci --progress=false
    - bash ./scripts/copy-env.sh ${ENV}
    - cd ios
    - bundle install --path ~/.gem
    - bundle exec pod install --repo-update
    - chmod og-rw ${SSH_PRIVATE_KEY}
    - GIT_SSH_COMMAND="ssh -i ${SSH_PRIVATE_KEY}" bundle exec fastlane ${ENV}
