require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  config = use_native_modules!

  use_react_native!(:path => config["reactnativepath"])

  # enables flipper.
  #
  # note that if you have use_frameworks! enabled, flipper will not work and
  # you should disable these next few lines.
  use_flipper!
end

target 'circular-dev' do
  shared_pods
end

target 'circular-demo' do
  shared_pods
end

target 'circular-prod' do
  shared_pods
end

post_install do |installer|
  flipper_post_install(installer)
end
