require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
pod 'RNCharts', :path => '../node_modules/react-native-charts-wrapper'

platform :ios, '12.1'

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # enables flipper.
  #
  # note that if you have use_frameworks! enabled, flipper will not work and
  # you should disable these next few lines.
  # //use_flipper!
end

# def xcode12_post_install(installer)
#   installer.pods_project.targets.each do |target|
#     target.build_configurations.each do |config|
#       config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
#     end
#   end
#   `sed -i -e  $'s/__IPHONE_10_0/__IPHONE_12_0/' Pods/RCT-Folly/folly/portability/Time.h`
# end

target 'Circular-Dev' do
  shared_pods
end

target 'Circular-Demo' do
  shared_pods
end

target 'Circular-Prod' do
  shared_pods
end

# post_install do |installer|
#   xcode12_post_install(installer)
#   flipper_post_install(installer)
#   installer.pods_project.build_configurations.each do |config|
#     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
#   end
# end



use_flipper!({ 'Flipper' => '0.95.0', 'Flipper-Folly' => '2.6.7', 'Flipper-DoubleConversion' => '3.1.7' })
post_install do |installer|

  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
  end
  react_native_post_install(installer)
  installer.pods_project.targets.each do |target|
    if target.name == "React-Core.common-AccessibilityResources"
      target.remove_from_project
    end
  end
end
