# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Initial setup"
  lane :setup do
    produce(app_name: 'App Dev', app_identifier: 'com.circular.circular.dev', skip_itc: true)
    produce(app_name: 'App Demo', app_identifier: 'com.circular.circular.demo', skip_itc: true)
    produce(app_name: 'App', app_identifier: 'com.circular.circular', skip_itc: true)
    match(type: "development", app_identifier: "com.circular.circular.dev", force_for_new_devices: true)
    match(type: "adhoc", app_identifier: "com.circular.circular.dev", force_for_new_devices: true)
    match(type: "adhoc", app_identifier: "com.circular.circular.demo", force_for_new_devices: true)
    match(type: "adhoc", app_identifier: "com.circular.circular", force_for_new_devices: true)
    match(type: "appstore", app_identifier: "com.circular.circular")
  end

  desc "Setup dev environment"
  lane :setup_dev do
    match(type: "development", app_identifier: "com.circular.circular.dev", force_for_new_devices: true)
  end

  desc "Build dev version"
  lane :dev do
    init_appstore_api_session()
    increment_build_number(build_number: number_of_commits)
    match(type: "adhoc", app_identifier: "com.circular.circular.dev", force_for_new_devices: true)
    build("Dev")
  end

  desc "Build demo version"
  lane :demo do
    init_appstore_api_session()
    increment_build_number(build_number: number_of_commits)
    match(type: "adhoc", app_identifier: "com.circular.circular.demo", force_for_new_devices: true)
    build("Demo")
  end

  desc "Build prod version"
  lane :prod do
    init_appstore_api_session()
    increment_build_number(build_number: number_of_commits)
    match(type: "adhoc", app_identifier: "com.circular.circular", force_for_new_devices: true)
    match(type: "appstore", app_identifier: "com.circular.circular", readonly: true)
    build("Prod")
  end
end

def init_appstore_api_session
  app_store_connect_api_key(
    key_id: ENV["APPSTORE_API_KEY_ID"],
    issuer_id: ENV["APPSTORE_API_ISSUER_ID"],
    key_content: ENV["APPSTORE_API_KEY"],
    in_house: false
  )
end

def build(flavor)
  build_app(scheme: "app-#{flavor}", configuration: "Release", output_name: "app-#{flavor}-release.ipa")
end
