# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

APPCENTER_APP_PREFIX = "Circular-Android-"
APPCENTER_OWNER = "BeTomorrow"

platform :android do
  desc "Build dev version"
  lane :dev do
    build("dev")
    appcenter("dev", true)
  end

  desc "Build demo version"
  lane :demo do
    build("demo")
    appcenter("demo", true)
  end

  desc "Build prod version"
  lane :prod do
    build("prod")
    upload_to_play_store(track: "alpha", release_status: "draft")
  end
end

def build(flavor)
  gradle(
    task: flavor === "prod" ? "bundle" : "assemble",
    build_type: "Release",
    flavor: flavor.capitalize,
    properties: {
      "versionCode": number_of_commits,
      "versionName": load_json(json_path: "../package.json")["version"]
    },
    flags: "--no-daemon"
  )
end

def appcenter(flavor, notify)
  appcenter_upload(
    app_name: "#{APPCENTER_APP_PREFIX}#{flavor.capitalize}",
    owner_name: "#{APPCENTER_OWNER}",
    destinations: "Collaborators,Circular",
    destination_type: "group",
    apk: "./app/build/outputs/apk/#{flavor}/release/app-#{flavor}-release.apk",
    release_notes: changelog(flavor),
    notify_testers: notify
  )
end

def changelog(flavor)
  begin
    result = appcenter_fetch_version_number(
      app_name: "#{APPCENTER_APP_PREFIX}#{flavor.capitalize}",
      owner_name: "#{APPCENTER_OWNER}")
    commits_count = number_of_commits - Integer(result["build_number"])
    commits_count = commits_count >= 1 ? commits_count : 1
  rescue
    commits_count = 1
  end
  changelog_from_git_commits(commits_count: commits_count)
  changelog = lane_context[SharedValues::FL_CHANGELOG]
  return "#{git_branch} :\n\n#{changelog}"
end
