# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

APPCENTER_APP_PREFIX = "Circular-Android-"
APPCENTER_OWNER = "Circular"

platform :android do
  desc "Build dev version"
  lane :dev do
    apkName = getApkName("dev", nil)
    build("dev", apkName, nil)
    appcenter("dev", apkName, true)
    codepush("dev")
  end

  desc "Build demo version"
  lane :demo do
    apkName = getApkName("demo", nil)
    build("demo", apkName, nil)
#    appcenter("demo", apkName, true)
    codepush("demo")
  end

  desc "Build staging version"
  lane :staging do |values|
    apkName = getApkName("staging", values[:buildName])
    build("staging", apkName, values[:buildName])
    appcenter("staging", apkName, true)
    codepush("staging")
  end

  desc "Build prod version"
  lane :prod do
    apkName = getApkName("prod", nil)
    build("prod", apkName, nil)
    codepush("prod")
    upload_to_play_store(track: "alpha", release_status: "draft")
  end
end

def getApkName(flavor, buildName)
  buildName ? "app-#{flavor}-#{buildName}-release" : "app-#{flavor}-release"
end

def build(flavor, apkName, buildName)
  gradle(
    task: (flavor === "prod") ? "bundle" : "assemble",
    build_type: "Release",
    flavor: flavor.capitalize,
    properties: {
      "versionCode": number_of_commits,
      "versionName": load_json(json_path: "../package.json")["version"],
      "buildName": buildName
    },
    flags: "--no-daemon"
  )
end

def appcenter(flavor, apkName, notify)
  appcenter_upload(
    app_name: "#{APPCENTER_APP_PREFIX}#{flavor.capitalize}",
    owner_name: "#{APPCENTER_OWNER}",
    destinations: "Collaborators,Circular",
    destination_type: "group",
    apk: "./app/build/outputs/apk/#{flavor}/release/#{apkName}.apk",
    release_notes: changelog(flavor),
    notify_testers: notify
  )
end

def codepush(flavor)
  Dir.chdir("..") do
    appcenter_codepush_release_react(
      app_name: "#{APPCENTER_APP_PREFIX}#{flavor.capitalize}",
      owner_name: "#{APPCENTER_OWNER}",
      deployment: "Production",
      target_version: "1"
    )
  end
end

def changelog(flavor)
  begin
    result = appcenter_fetch_version_number(
      app_name: "#{APPCENTER_APP_PREFIX}#{flavor.capitalize}",
      owner_name: "#{APPCENTER_OWNER}")
    commits_count = number_of_commits - Integer(result["build_number"])
    commits_count = commits_count >= 1 && commits_count < 20 ? commits_count : 1
  rescue
    commits_count = 1
  end
  changelog_from_git_commits(commits_count: commits_count)
  changelog = lane_context[SharedValues::FL_CHANGELOG]
  return "#{git_branch} :\n\n#{changelog}"
end
